package br.com.simnetwork.BotByCasseb.model.entity.dialog.structure;

public enum StepType {
	
	SIMPLEMESSAGE,
	REQUESTCONTACT,
	REQUESTSTRING,
	REQUESTINLINEOPTION,
	REQUESTINLINEOPTIONLINK,
	INSERT,
	REQUESTCONFIRMATION,
	REQUESTRECORD,
	LINK,
	SHOWRECORD,
	INSERTDECISION,
	UPDATE,
	DELETE,
	DELAY

}
